name: hello-world-action
run-name: ${{github.actor}} is saying hello world!
on:
  workflow_call:
  push:
    branches:
      - 'main'
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"